# version: 0.2

# # env:
# #   variables:
# #     VITE_API_BASE_PATH: "http://test-loadbalancer-2071423490.us-east-1.elb.amazonaws.com"
# #     VITE_PROMPT_API_BASE_PATH: "http://test-loadbalancer-2071423490.us-east-1.elb.amazonaws.com/api/"
# #     VITE_SOCKET_BASE_PATH: "/"

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18  # Update to Node.js 18 to match the required version
#     commands:
#       - echo "Installing dependencies..."
#       - npm -v
#       - node -v
#       - echo "VITE_API_BASE_PATH: $VITE_API_BASE_PATH"
#       - echo "VITE_PROMPT_API_BASE_PATH: $VITE_PROMPT_API_BASE_PATH"
#       - echo "VITE_SOCKET_BASE_PATH: $VITE_SOCKET_BASE_PATH"
#       # Replace the values in the .env.dev file with the environment variables
#       - sed -i "s|VITE_API_BASE_PATH=.*|VITE_API_BASE_PATH=$VITE_API_BASE_PATH|" .env.dev
#       - sed -i "s|VITE_PROMPT_API_BASE_PATH=.*|VITE_PROMPT_API_BASE_PATH=$VITE_PROMPT_API_BASE_PATH|" .env.dev
#       - sed -i "s|VITE_SOCKET_BASE_PATH=.*|VITE_SOCKET_BASE_PATH=$VITE_SOCKET_BASE_PATH|" .env.dev
#   pre_build:
#     commands:
#       - npm install  # Install all npm dependencies for the Angular project
#   build:
#     commands:
#       - echo "Building the Angular application..."
#       # - npm run devbuild
#       - export $(cat .env.dev | xargs) && npm run devbuild
#       # - ng build  --configuration $ENV # Build the Angular app in development mode
#   post_build:
#     commands:
#       - echo "Build complete. Preparing to upload to S3..."
#       - ls -la
#       - ls dist/ -la
#       - aws s3 sync dist/ s3://rfp-s3-frontend-us-east-1-414432075221 --delete  # Sync the contents of dist/ with the S3 bucket
# artifacts:
#   files:
#     - '**/*'  # Collect the built application from the dist folder
#   base-directory: dist/  # The base directory for the output artifact (adjust if needed)
 
# cache:
#   paths:
#     - node_modules/**  # Cache node_modules to speed up future builds


version: 0.2

# env:
#   variables:
#     VITE_API_BASE_PATH: "http://test-loadbalancer-2071423490.us-east-1.elb.amazonaws.com"
#     VITE_PROMPT_API_BASE_PATH: "http://test-loadbalancer-2071423490.us-east-1.elb.amazonaws.com/api/"
#     VITE_SOCKET_BASE_PATH: "/"

phases:
  install:
    runtime-versions:
      nodejs: 18  # Update to Node.js 18 to match the required version
    commands:
      - echo "Installing dependencies..."
      - npm -v
      - node -v
      - printenv
      # - echo "VITE_API_BASE_PATH: $VITE_API_BASE_PATH"
      # - echo "VITE_PROMPT_API_BASE_PATH: $VITE_PROMPT_API_BASE_PATH"
      # - echo "VITE_SOCKET_BASE_PATH: $VITE_SOCKET_BASE_PATH"
      # Replace the values in the .env.dev file with the environment variables
      # - sed -i "s|VITE_API_BASE_PATH=.*|VITE_API_BASE_PATH=$VITE_API_BASE_PATH|" .env.dev
      # - sed -i "s|VITE_PROMPT_API_BASE_PATH=.*|VITE_PROMPT_API_BASE_PATH=$VITE_PROMPT_API_BASE_PATH|" .env.dev
      # - sed -i "s|VITE_SOCKET_BASE_PATH=.*|VITE_SOCKET_BASE_PATH=$VITE_SOCKET_BASE_PATH|" .env.dev

  pre_build:
    commands:
      - npm install  # Install all npm dependencies for the project

  build:
    commands:
      - echo "Building the Angular application..."
      - export $(cat .env.dev | xargs) && npm run devbuild

  post_build:
    commands:
      - echo "Build complete. Preparing to upload to S3..."
      - ls -la
      - cat .env.dev
      - ls dist/ -la
      - aws s3 sync dist/ s3://rfp-s3-frontend-us-east-1-414432075221 --delete  # Sync the contents of dist/ with the S3 bucket

artifacts:
  files:
    - '**/*'  # Collect the built application from the dist folder
  base-directory: dist/  # The base directory for the output artifact (adjust if needed)

cache:
  paths:
    - node_modules/**  # Cache node_modules to speed up future builds
