version: 0.2

env:
  parameter-store:
    VITE_API_BASE_PATH: "/rfp/dev/VITE_API_BASE_PATH"
    VITE_PROMPT_API_BASE_PATH: "/rfp/dev/VITE_PROMPT_API_BASE_PATH"
    VITE_SOCKET_BASE_PATH: "/rfp/dev/VITE_SOCKET_BASE_PATH"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm -v && node -v

      - echo "Replacing the contents of the .env.dev file with actual values..."
      - sed -i "s|VITE_API_BASE_PATH=.*|VITE_API_BASE_PATH=$VITE_API_BASE_PATH|" .env.dev
      - sed -i "s|VITE_PROMPT_API_BASE_PATH=.*|VITE_PROMPT_API_BASE_PATH=$VITE_PROMPT_API_BASE_PATH|" .env.dev
      - sed -i "s|VITE_SOCKET_BASE_PATH=.*|VITE_SOCKET_BASE_PATH=$VITE_SOCKET_BASE_PATH|" .env.dev

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - echo "Building the Angular application..."
      - export $(cat .env.dev | xargs) && npm run devbuild

  post_build:
    commands:
      - echo "Build complete. Preparing to upload to S3..."
      - ls -la
      - ls dist/ -la
      - aws s3 sync dist/ s3://rfp-s3-frontend-us-east-1-414432075221 --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist/

cache:
  paths:
    - node_modules/**
