version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g typescript@latest
      - npm install
      - npm -v
      - node -v
      - |
        aws ssm get-parameters-by-path \
            --path "/rfp/dev/FE" \
            --recursive \
            --with-decryption \
            --query "Parameters[].[Name,Value]" \
            --output text | while read name value; do
            key=$(basename "$name")
            echo "${key}=${value}" >> .env
        done
      - echo "Environment variables written to .env file:"
      - cat .env

  pre_build:
    commands:
      - echo "Validating environment variables..."
      - test -s .env || (echo "Missing .env file or empty"; exit 1)
      - npm install

  build:
    commands:
      - echo "Building the Angular application..."
      - export $(cat .env | xargs) && npm run devbuild

  post_build:
    commands:
      - echo "Build complete. Preparing to upload to S3..."
      - ls -la
      - ls dist/ -la
      - aws s3 sync dist/ s3://rfp-dev-app-frontend-us-east-1-414432075221 --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist/

cache:
  paths:
    - node_modules/**
