version: "3.9"

services:

  rfp:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_PATH: http://localhost:3000
      VITE_PROMPT_API_BASE_PATH: http://localhost:8000
      VITE_SOCKET_BASE_PATH: /
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
