const LAST_UPLOAD_CSV_DATE_FORMAT = "D MMMM YYYY";
const PROMOS_DATE_FORMAT = "D MMMM YYYY HH:mm";

const DEFAULT_DATE_FORMAT = "YYYY-MM-DD";
const DEFAULT_TIME_FORMAT = "HH:mm";
const DEFAULT_DATE_TIME_FORMAT = "YYYY-MM-DD HH:mm";
const PAYLOAD_DATE_TIME = "YYYY-MM-DDTHH:mm:ss";
const DOC_EXP_DATE = "DD/MM/YYYY";

export {
  LAST_UPLOAD_CSV_DATE_FORMAT,
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  DEFAULT_DATE_TIME_FORMAT,
  PAYLOAD_DATE_TIME,
  DOC_EXP_DATE,
  PROMOS_DATE_FORMAT,
};
