const {
  VITE_API_BASE_PATH: API_BASE_PATH,
  VITE_SOCKET_BASE_PATH: SOCKET_BASE_PATH,
  VITE_GOOGLEMAP_ACCESS_TOKEN: GOOGLEMAP_ACCESS_TOKEN,
  VITE_PROMPT_API_BASE_PATH: PROMPT_API_BASE_PATH,
} = import.meta.env;

export {
  API_BASE_PATH,
  SOCKET_BASE_PATH,
  GOOGLEMAP_ACCESS_TOKEN,
  PROMPT_API_BASE_PATH,
};
